detectors:
  IrresponsibleModule:
    enabled: false

  FeatureEnvy:
    exclude:
      - ROM::Mongo::Dataset#insert
      - ROM::Mongo::Schema#to_output_hash

exclude_paths:
  - spec/support/helpers
